namespace: azureredhatopenshift
name: hcp
version: 1.0.0
readme: README.md
authors:
  - Andrew Denton <adenton@redhat.com>
description: A collection of roles to install and upgrade Azure Red Hat OpenShift (ARO) Hosted Control Plane (HCP) clusters
license:
  - Apache-2.0
tags: []
dependencies: {
  "azure.azcollections": "3.3.1"
}
repository: https://github.com/openshift/aro-e2e
issues: https://github.com/openshift/aro-e2e/issues
build_ignore: []
